---
- name: SSH connection to devices in Inventory
  hosts: renamed,!taz
  connection: ssh
  gather_facts: no
  become: true

  vars:
    username: "maddard"

  tasks:
    - name: Ensure group "funkytown" exists
      ansible.builtin.group:
         name: funkytown
         state: present

    - name: creat user and add to group funkytown
      ansible.builtin.user:
        name: "{{ username }}"
        groups: funkytown
   
